### ISSUE TITLE
Tracker: tile-converter issues

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1162]
- [x] Add instructions for how to serve the converted tileset (e.g. from SLPK or file tree)
- [x] [tile converter command line docs](https://loaders.gl/modules/tile-converter/docs/cli-reference/tile-converter) Add command line showing how to install the `tile-converter` tool
- [x] Loader warnings when running `npx tile-converter --input-type 3dtiles --tileset https://assets.cesium.com/29328/tileset.json --name CairoLayer --max-depth 10`

<img width="681" alt="Screen Shot 2021-02-08 at 7 20 17 AM" src="https://user-images.githubusercontent.com/7025232/107241682-115f9680-69e0-11eb-83d2-552eba49b8bd.png">

<img width="468" alt="Screen Shot 2021-02-08 at 7 09 21 AM" src="https://user-images.githubusercontent.com/7025232/107238487-bd9f7e00-69dc-11eb-8e08-f080f58d01ff.png">

**Comment by ibgreen** [comment]
The fetch warning should be an easy to fix. The `baseUri` is a little trickier.

**Comment by h3rb** [comment]
Bumping this because I had posted in Discussions hoping there was a known solution.  https://github.com/visgl/loaders.gl/discussions/1362

**Comment by ibgreen** [comment]
@dryabinin-actionengine Can you provide an update?

**Comment by dryabinin-actionengine** [comment]
@ibgreen  It will be good if @h3rb be able to provide this particular `3DTiles` tileset for debugging purpose to us. Also will take a look at other warnings.

**Comment by dryabinin-actionengine** [comment]
@ibgreen Fix for tile-converter warnings - [PR](https://github.com/visgl/loaders.gl/pull/1365)
