### ISSUE TITLE
tracker: I3S/3D Tile debugging

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1246]
- [x] Show view frustum in a minimap - fix perf issues in #636
- [x] Enable debug BoundingBox view  **P0**
- [x] Color tiles
- [x] Show normals
- [x] Show UVs
- [x] Show wireframes
- [ ] Clean up 3d-tiles example: Stats Widget Handling **P1** @dryabinin-actionengine  P1
- [ ] Improve Stats collection in loaders.gl
- [ ] Correctly calculate memory usage for compressed textures in loaders.gl 

Also see https://github.com/visgl/loaders.gl/issues/356
