### ISSUE TITLE
tracker: Merge Back code in luma and deck

### ISSUE THREAD

**Issue by belom88** [visgl/loaders.gl#1324]
Comparing PRs:
- [x] Stop loading option: [Stop loading option PR](https://github.com/visgl/loaders.gl/pull/1376)
- [x] Vertex colors: [Vertex colors PR](https://github.com/visgl/deck.gl/pull/5756)
- [x] Picking colors: [Picking colors PR](https://github.com/visgl/deck.gl/pull/5757)
- [x] Multiple viewports: [Multiple viewports PR](https://github.com/visgl/deck.gl/pull/5758)
- [x] Pass props for Tile coloring: [Pass props for Tile coloring PR](https://github.com/visgl/deck.gl/pull/5759)
- [x] Support uvRegions: [Support uvRegions PR](https://github.com/visgl/deck.gl/pull/5760)
- [x] PBR Material: [PBR Material PR](https://github.com/visgl/deck.gl/pull/5761)
- [x] Documentation for getTIleColor function: [Documentation PR](https://github.com/visgl/deck.gl/pull/5814)

@luma.gl

- [x]  from https://github.com/visgl/loaders.gl/blob/master/examples/experimental/i3s-17-and-debug/luma/gltf-material-parser.js to https://github.com/visgl/luma.gl/blob/master/modules/experimental/src/gltf/gltf-material-parser.js
  - [x] Support compressed textures

@deck.gl

- [x] from https://github.com/visgl/loaders.gl/blob/master/examples/experimental/i3s-17-and-debug/mesh-layer/simple-mesh-layer-vertex.glsl.js to https://github.com/visgl/deck.gl/blob/master/modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-vertex.glsl.js
  - [x] uv-region support
  - [x] Picking colors logiс
  - [x] PBR material support
- [x] from https://github.com/visgl/loaders.gl/blob/master/examples/experimental/i3s-17-and-debug/mesh-layer/simple-mesh-layer-fragment.glsl.js to https://github.com/visgl/deck.gl/blob/master/modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer-fragment.glsl.js
  - [x] PBR material support
  - [x] Support vertex colors for textured non-material datasets
- [x] from https://github.com/visgl/loaders.gl/blob/master/examples/experimental/i3s-17-and-debug/mesh-layer/mesh-layer.js to https://github.com/visgl/deck.gl/blob/master/modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js
  - [x] getShaders() - include pbr module;
  - [x] initializeState() - add pickingColors attribute
  - [x] draw({uniforms}) - u_Camera uniform for PBR support
  - [x] getModel(mesh) - PBR support, uv-region support
  - [x] setTexture(texture) - PBR support
  - [x] setMaterial(material) - update material (for the case when we need to replace texture with debug texture)
  - [x] calculatePickingColors(attribute) - object picking
- [x] from https://github.com/visgl/loaders.gl/blob/master/examples/experimental/i3s-17-and-debug/tile-layer/tile-layer.js to https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/tile-3d-layer/tile-3d-layer.js
  - [x] _updateTileset(tileset3d) - multiple viewports supports, `loadTiles` options support (to stop loading of tiles)
  - [x] _makeSimpleMeshLayer(tileHeader, oldLayer) - pass props for tile coloring, PBR and picking
  - [x] function getMeshGeometry(contentAttributes) - new attributes support: uvRegions, colors, featureIds

**Comment by belom88** [comment]
I've made diff files where is was possible https://github.com/visgl/loaders.gl/pull/1325
