### ISSUE TITLE
tracker: Tile optimizations

### ISSUE THREAD

**Issue by Avnerus** [visgl/loaders.gl#1406]
The goal is to merge back tile optimizations that were done for photogrammetry, making sure they are compatible with point clouds and i3s.

 - [x] Make sure performance is equal or above the current stable version for i3s and pointclouds.
 - [x] Make `thorttleRequests` the default.
 - [x] Add `loadOptions` passing to `Tileset3D`.
 - [x] Documentation for the options: `viewDistanceScale` , `updateTransforms` 
 - [x] Documentation for new property `selectionDepth`
 - [x] Tile loading callback to enable external async loading of tile content.
 - [ ] New tests if needed.
