### ISSUE TITLE
Tracker: gis category - support schema and layers

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1430]
We want to be able to return (optional) arrow schemas from geospatial loaders

- [ ] Update GIS category docs
- [ ] Add types for GIS data format (return type for GIS loaders)
- [ ] Update Shapefile loader
- [ ] Update KML, GPX, TCX
- [ ] ...

### Background

The following loaders are listed in https://loaders.gl/docs/specifications/category-gis

gis object:
- `schema?`:  
- `data`: features, binary etc.
- `encoding?: string`
- `projection?: string`
- `loaderData`: object - Loader specific data`
 
shapefile specific
- prj?: string
- shx: ...
- header: shapeHeader,

| Loader            | `geojson` | `binary` | `raw` | `batch` | comments |
| --- | --- | --- | --- |
| `GPXLoader` | a FeatureCollection | attributes object | parsed XML |
| `KMLLoader` | a FeatureCollection | attributes object | parsed XML |
| `TCXLoader` | a FeatureCollection | attributes object | parsed XML |
| `MVTLoader` | layers with FeatureCollections | 
| `GeoJSONLoader` | 
| `ShapefileLoader` | gis object | gis object | - | gis object | 
| `SHPLoader` |
| `FlatGeobufLoader` | a FeatureCollection | - | - |
| `GeoPackageLoader` | layers with FeatureCollections | - | - |
| `WKBLoader` | a single geojson geometry (not feature) | - | - |
| `WKTLoader` | a single geojson geometry (not feature) |  - | - | 

Tables category

| Loader            | `json` | `binary` | `raw` | comments |
| --- | --- | --- | --- |
| `DBFLoader` | 

### Problem: Atomic loaders

Currently
- Where to put schema?
- Change return values?
- Add `metadata` option that returns a wrapper object?

### Problem: Non binary loaders

Focus on binary loaders. Omit schema from non-binary loaders for now

### Problem: Batched Loaders

- Schema: There is already support for an optional metadata batch, that could accommodate the schema.
- Layers: ???

# Roadmap

- Binary support for WKT / WKB?
-

**Comment by ibgreen** [comment]
@kylebarron Kept thinking about this. One way to unify the gis and gis-layers subcategories would be to store "primary" layer in data and additional layers in a `layers` map, something like.

- `category`: `string` - `gis`
- `schema?`: `Schema` - Apache Arrow style schema
- `format`: `string` - The encoding of `data` layers, corresponds to `options.gis.format`
- `layerName`: `string` - The name of the layer in `data`
- `data`: `*` - Data is formatted according to `options.gis.format`
- `layers`: `{name, schema, loaderMetadata, data}[]` - Additional layers
- `loaderMetadata?`: `object` - Loader specific metadata, see documentation for each loader.

Would be easy enough for the app to check for `layers` and add the primary layer to the map.

Layer GIS loaders could offer an option to only load one (named, first or "default") layer.

**Comment by ibgreen** [comment]
@belom88 FYI
