### ISSUE TITLE
tracker: Arrow Schema support

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1443]
### General
- [ ] Documentation for Schemas
- [ ] Handle schema serialization/deserialization from workers

### GeoPackage issues - See discussions in #1428
- [ ] Need conventions for encoding dates in schemas, and converting to JS / Arrow
- [ ] Need conventions for encoding geojson feature / geometry columns
- [ ] Need conventions for non-arrow columns
- [ ] Need conventions for mappings between physical and logical column names in field metadata

### Loader support for Schemas

Binary loaders in progress
- [ ] DBF
- [ ] PCD
- [ ] OBJ

Binary loaders 
- [ ] DracoLoader
- [ ] LASLoader

Tiled loaders
- [ ] I3SLoader
- [ ] Tile3DLoader

**Comment by belom88** [comment]
> DBF

I see DBF Schema is already implemented in `shapefile` module.

**Comment by belom88** [comment]
I'm making schema for DracoLoader. A PR is coming soon...

**Comment by ibgreen** [comment]
Closing for inactivity, but adding link to future release tracker for reference.
