### ISSUE TITLE
Tracker: update I3S application with new deck.gl version

### ISSUE THREAD

**Issue by belom88** [visgl/loaders.gl#1477]
- [ ] When all tiles are loaded, application doesn't display changing of some debug options:
  - Use different viewports;
  - Select bounding volume type (MBS/OBB);
  
  If change viewport state (tilt / rotate / zoom), the application starts reacting on the option.

- [ ] Use different viewports mode: minimap tiles are shown on main viewport;

- [ ] Tile coloring doesn't work;

- [ ] Wireframe mode doesn't work;

- [ ] Picking selects buildings instead of tiles.
