### ISSUE TITLE
Remove TypeScript excludes Tracker

### ISSUE THREAD

**Issue by dryabinin-actionengine** [visgl/loaders.gl#1534]
We have to enable type checking from [list](https://github.com/visgl/loaders.gl/blob/master/tsconfig.json#L91).

- [ ] "modules/tiles/test/**/*"
- [ ] "modules/tile-converter/src/**/*"
- [ ] "modules/tile-converter/test/**/*"
- [ ] "modules/i3s/test/**/*"
- [ ] "modules/textures/test/**/*"
- [ ] "modules/gltf/test/**/*"
- [ ] "modules/excel/test/**/*"
