### ISSUE TITLE
Tracker: @loaders.gl/tiles

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#164]
Open tasks moved to #1245 

--- 

## loaders.gl v2.0 (for deck.gl 8.0)

glTF-based Tile parsing
- [x] `@loaders.gl/gltf`: `Tile3DLoader` and `GLTFLoader` to wait for all sub loaders **P0** (@ibgreen) 
- [x] `@loaders.gl/core`: Improve support for sub-loaders **P0**  @ibgreen 
- [x] `@loaders.gl/core`: Move loader options into nested sub objects (to simplify sending options to sub-loaders) @ibgreen **P0**

---
---
## loaders.gl v1.3 (for deck.gl 7.3)

Tile3DLayer
- [x] Tests for `Tile3DLayer` **P0** (@xintongxia)
- [x] Audit `Tile3DLayer` **P0** (@xintongxia)
- [x] Move: `Tile3DLayer` to deck.gl **P0** (@jianhuang01)
- [x] Document `Tile3DLayer` **P0** (@xintongxia)
- [x] `Tile3DLayer` cleanup: Ion Asset Handling **P0** (@xintongxia)
- [x] `Tile3DLayer` cleanup: General **P0** (@xintongxia)

3d-tiles example
- [x] Clean up 3d-tiles example: Ion Asset Handling **P0** (@ibgreen)
- [x] Add ion logo when loading from Cesium ion server https://cesium.com/press/ **P0** (@ibgreen)
- [x] Fix the stats widget below tile selector (use stats object from 3d-tiles)
- [x] Create reference sandbox to test tilesets in Cesium (@xintongxia)

3d-tiles module documentation
- [x] Improve documentation of generic "3d-tiles loader category" **P0** (@xintongxia / @ibgreen)
- [x] Improve documentation of `Tileset3D` class **P0** (@ibgreen)

glTF-based Tile parsing
- [x] Fix WebGL issues (texture!?!) with glTF tilesets (@jianhuang01)
- [x] Fix transform issues with gltf tilesets (@OmarShehata)
- [x] Load photogrammetry-based tilesets (e.g vricon) (@xintongxia)
- [x] `Tile3DLayer`: Map instanced model tile data to deck.gl `ScenegraphLayer` attributes #246 (@xintongxia) 
- [x] `Tile3DLayer`: Support batched gltf tiles #246 (@xintongxia)

Point Cloud Parsing
- [x] Support quantized/scaled positions on GPU (@xintongxia / @ibgreen) 
- [x] Support quantized/scaled positions on CPU (@xintongxia / @ibgreen) 
- [x] Support oct-encoded normals on CPU (@xintongxia) 
- [x] Port attribute compression lib (oct encoding) #321 (@ibgreen)
- [x] Support different color arrays without copying (@ibgreen/@xintongxia)

3d-tiles module code
- [x] Add request synchronizer to avoid loading tiles no longer in view (@ibgreen)
- [x] Fix/confirm cache unloading **P0** (@loshjawrence)
- [x] Perf: Solve excessive worker creation overhead (worker pool?) **P0**
- [x] `DracoWorkerLoader` is not working (@xintongxia)
- [x] Handle nested tilesets (@loshjawrence / @ibgreen)
- [x] Calculate memory use per tile during parsing to enable cache unloads, see #328 (@ibgreen)
- [x] Use probe.gl stats object to collect stats on loading and memory use (@ibgreen)

Tileset3D refactor
- [x] ensure all loading/unloading and associated state keeping/stats tracking goes through a single set of clearly defined methods on `Tileset3D`.
- [x] refactor `Tileset3DTraversal` so that it does not access Tileset directly (@ibgreen)
- [x] refactor `Tileset3D` into public/private methods (@ibgreen)

deck.gl issues
- [x] Bug: `ScenegraphLayer` `opacity` prop is broken (@jianhuang01)
- [x] Bug: `ScenegraphLayer` `modelMatrix` is broken **P0** (@jianhuang01)
- [x] Bug: `ScenegraphLayer` PBR color (not texture) is broken (@jianhuang01)
- [x] Bug: Unnecessary attribute copy in deck.gl (@jianhuang01)

# loaders.gl v1.2 (for deck.gl 7.2?)

Traversal
- [x] Integrate tileset traversal with math.gl/culling (@loshjawrence)
- [x] Implement tile cache (@loshjawrence)
- [x] Implement basic tileset traversal (@loshjawrence)

glTF-based Tile parsing
(@xintongxia)
- [x] Demo: Fix `ScenegraphLayer` rendering for sync data? (@georgios-uber)
- [x] Demo: Map batched model to deck.gl `ScenegraphLayer`? (@ibgreen)
- [x] Connect 3DTile parsers to glTF parser (@ibgreen)
- [x] Enable parsing of embedded GLBs at arbitrary byte offsets (@ibgreen) #163 

# loaders.gl v1.1 (for deck.gl 7.1)

Use the transforms in the tileset and the tile to position the tiles correctly on the base map.

- [x] Add a base map to DEMO
- [x] Show 3D tiles correctly positioned on top of base map (@xintongxia)
- [x] Create a CompositeLayer that takes a Tileset3D and renders the various subtiles (@xintongxia)
- [x] Load all tiles in tileset (@ibgreen/@xintongxia)
- [x] Implement `Ellipsoid` class to enable conversion of WSG84 "cartesians" to cartographic/lnglatz. (@ibgreen)
- [x] Implement `Tile3DHeader.loadContent()` (@ibgreen) #224
- [x] Create `Tile3DHeader`s for all tiles in tileset (@ibgreen)
- [x] Parse tilesets and create `Tileset3D` class, unit tests (@ibgreen)

### Math primitives
- [x] Geospatial: Refined Port `Ellipsoid` etc classes. #223
- [x] Culling: Refined Port `OrientedBoundingBox`, `BoundingSphere`, `PerspectiveFrustum`, `CullingVolume` classes.
- [x] Geospatial: Raw Port `Ellipsoid` etc classes. (@ibgreen)
- [x] Culling: Raw Port `OrientedBoundingBox`, `BoundingSphere`, `PerspectiveFrustum`, `CullingVolume` classes. (@ibgreen)

### Point Clouds
- [x] Show point cloud correctly positioned on top of base map (@xintongxia)
- [x] Demo: Map point cloud data to deck.gl `PointCloudLayer` attributes  (@xintongxia)
- [x] Implement Draco support for point cloud tiles (@xintongxia)
- [x] Implement support for various point cloud formats (@xintongxia)
- [x] Implement batch table parsing (@ibgreen)

### Initial Tile Parsing
- [x] Add unit test data from Cesium repo (@ibgreen)
- [x] Implement composite tile parser (@ibgreen)
- [x] Implement point cloud tile parser (@ibgreen)
- [x] Implement instanced model tile parser (@ibgreen)
- [x] Implement batched model tile parser (@ibgreen)

**Comment by ibgreen** [comment]
@mcasebeer FYI

**Comment by veikkoeeva** [comment]
That `Implement vector tiles`, does it refer to tilesets in some format such as Mapbox vector tiles, something else or yet undefined? I see https://github.com/uber/deck.gl has integration with Mapbox, hence the question. Besides the questions, I would be interest to know if there are thoughts about map applications regarding this.

Also apologies if this isn't the appropriate place to these sort of questions.

**Comment by ibgreen** [comment]
> That Implement vector tiles, does it refer to tilesets in some format such as Mapbox vector tiles

@veikkoeeva This refers to the vector tile variant of the 3D tiles specification. I believe they are still experimental. Maybe @loshjawrence can confirm.

We do have an implementation of the mapbox vector tile loading in our companion framework deck.gl. It might make sense to move that to loaders.gl.

https://github.com/uber/deck.gl/blob/master/docs/layers/tile-layer.md

Not sure if that addresses your needs/interests?

**Comment by veikkoeeva** [comment]
@ibgreen Partially, I think. I've been thinking how to combine something like BabylonJS glTF assets together with georeferenced "charting data" and maps; maybe have the assets themselves be of chart like visualization data that ought be placed on a map and be interactive. Surely all this looks like becoming an interesting space.

**Comment by donmccurdy** [comment]
Do you plan to support the [declarative styling specification](http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html#257) and expressions from the 3D Tiles specification? Or would that be out of scope for this project? If not, do you know whether an open source, renderer-agnostic implementation exists yet?

**Comment by ibgreen** [comment]
>Do you plan to support the declarative styling specification and expressions from the 3D Tiles specification? 

@donmccurdy Ideally we'd like to support the full 3D tiles standard with all options and extensions, but due to the significant amount of work involved in this effort we decided not to tackle the styling part in the first version.

How far we go after that will depend a bit on uptake and interest (and yes, naturally, your question counts as interest).

From my quick review of the Cesium styling code it looks like (at least the framework independent parts of) styling support should be a fairly small and self-contained addition, it might even be a good fit for an external PR 

Once we have dynamic tileset traversal in place, we should be able to wrap up the initial version and then we should make a list of the gaps (including styles) and re-evaluate efforts and priority.

>  If not, do you know whether an open source, renderer-agnostic implementation exists yet?

I am not aware of any, but as mentioned, the Cesium code base is open source, clean and has great test coverage, I have found it to be a very solid base for porting work.

Copying some Cesium folks @joshlawrence @lilleyse

**Comment by donmccurdy** [comment]
> From my quick review of the Cesium styling code it looks like (at least the framework independent parts of) styling support should be a fairly small and self-contained addition, it might even be a good fit for an external PR.

Perhaps even an external module. 🤔 I'm imagining something similar to d3-scale that takes a style object as input and can then return visual properties for any given feature on demand:

```js
import { styleEval } from '@3dtiles/style-eval';

const style = styleEval({ ... });
const fillColor1 = style.getFillColor( feature1 );
const fillColor2 = style.getFillColor( feature2 );
```

**Comment by ibgreen** [comment]
@donmccurdy I get the sense that you are looking for a reusable styling module to use in an independent context (i.e. not as a 3D Tiles feature?)

We also have stylesheet support in our XVIZ/streetscape.gl autonomy solutions:

**Comment by donmccurdy** [comment]
> I get the sense that you are looking for a reusable styling module to use in an independent context (i.e. not as a 3D Tiles feature?)

I'm just curious at this point. I have possible use cases for 3D tiles feature data alone, for the style rules alone, and for both, but it's too early to say whether I'll move forward with anything. 

The style rules in 3D Tiles seem to be the closest equivalent thing to being "standard" (it's an OGC Community Standard, at least) which makes them of some independent interest to me. Mapbox's style specification and the XVIZ styling looks functionally solid, but not on a standards track.

**Comment by ibgreen** [comment]
> The style rules in 3D Tiles seem to be the closest equivalent thing to being "standard" 

That is a good point. A downside is perhaps that 90% of the currently defined style fields are marked as experimental and are not officially part of the standard, but that could probably be addressed with a revision. 

> I have possible use cases for 3D tiles feature data alone, for the style rules alone, and for both, but it's too early to say whether I'll move forward with anything.

Understood. I really like the idea of loaders.gl being able to provide those pieces as independent building block. 

I just spent some time checking what it would take to do an initial framework independent port of the 3D tile styles class (#262). It does pull in a bit more code than I originally thought, but it still seems like a basic port could be completed within a day or so, allowing styles to be created and features to be evaluated against it.

**Comment by pjcozzi** [comment]
> That is a good point. A downside is perhaps that 90% of the currently defined style fields are marked as experimental and are not officially part of the standard

@ibgreen could you point me to these fields?  There is a well-defined styling spec that is part of the 3D Tiles OGC Community Standard.  There may be some "experimental ideas" beyond that but the core should be well defined at https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/Styling/README.md

**Comment by ibgreen** [comment]
@pjcozzi - I was just looking at https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileStyle.html, where 23 of the actual styles are marked as experimental. I haven't compared with the actual styling spec.

**Comment by pjcozzi** [comment]
Ah, thanks @ibgreen, yes those properties are mostly for billboard/label fields that are not yet part of the 3D Tiles OGC Community Standard.  Those are documented in this branch of the spec for interested folks: https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/3d-tiles-next/Styling/README.md
