### ISSUE TITLE
Tracker: 3.1-release

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#1917]
QA 
- [ ] test tile converter

Build
- [x] Generate .d.ts files
- [ ] Fix d.ts file generation for core and csv

Docs
- [ ] ParquetLoader docs
