### ISSUE TITLE
Tracker: @loaders.gl/potree

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#212]
### Related
- #257 
- #424

### Parsing code
- [ ] Implement Binary Attribute parser
- [x] Implement HRC parser #349
- [x] Add test cases to loaders.gl folder.

## Conversion
- [ ] Convert HRC files and top-level json to standardized "3D tile category" data
- [ ] Define and set standardized "metadata" fields for tileset
- [ ] Calculate Bounding Boxes for each hierarchy node.

### Tile traversal code.
- [ ] Update traversal algorithm to handle potree characteristics
- [ ] Update traversal to handle non-geospatial coordinates

### Example
- [ ] Update example to handle non-geospatial clouds (e.g. scans of statues etc)
- [ ] Use COORDINATE_SYSTEM.IDENTITY, different controller, disable base map etc.

### Notes on the `potree` data format:

- Only point clouds, using a basic octree dividing a top-level axis oriented bounding box (no kd-tree and advanced bounding regions like in 3D tiles). 
- Because of the simple octree division system, the "tile files" have a simple predictable naming scheme `r0703...` where each digit hierarchically determines a sub-octant (0-7)
- The "tile files" are either LAS or LAZ encoded (which we already support) or just contain concatenated binary buffers for positions, colors etc.
- The points in the tiles are always additive (parent tile is rendered in addition to child tile).
- There is a minimum distance between points in the top-level tiles, which halves with each octree division.
- Just like 3D tiles, the "magic" of potree lies in the traversal and rendering code (selecting which tiles to load and render etc). We should be able to render potree data sets with a small additional effort.

### 3D Tiles
- [Cesium Commercial Tiling Service](https://cesium.com/3d-tiling-pipeline/)
- [github: 3d-tiles-tools](https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/tree/master/tools) - Processes tile files but does not generate tiles

### Potree
- [Generating Potree] (https://wiki.cyverse.org/wiki/display/~tyson_swetnam/Generating+Potree+point+clouds)
- [github: Potree Converter](https://github.com/potree/PotreeConverter)
- [github: generator-potree](https://github.com/openearth/generator-potree)

### EPT Tools

- [EPT Tools](https://github.com/connormanning/ept-tools) project (which also demonstrates conversion from EPT->3D-Tiles) in Javascript, and PDAL's [EPT reader](https://github.com/PDAL/PDAL/blob/master/io/EptReader.cpp) in C++.

### PDAL

- I3S point cloud is implemented in [PDAL ](https://github.com/PDAL/PDAL/tree/master/plugins/i3s) and the LEPCC encoder it uses is known to compile to JavaScript, but the PDAL project hasn't done any of that so far.

**Comment by m-schuetz** [comment]
Interesting stuff! Just to let you know, the binary potree format is about to have a minor update in the following weeks. Instead of a predefined set of attributes, it will be possible to specify arbitrary attributes including name, size, type, description for each attribute. The version attribute in cloud.js will be incremented to identify files with the new format.

**Comment by ibgreen** [comment]
@m-schuetz Wow, the potree creator. You started all of this... welcome to loaders.gl!

>  it will be possible to specify arbitrary attributes including name, size, type, description for each attribute.

That sounds like a great addition to the potree format, thanks for the heads up! It should not be hard for us to support that and maybe also make use of some additional attributes.

**Comment by ibgreen** [comment]
@m-schuetz If you are curious about the vision for potree support in loaders.gl, you can see the diagram in the [blog post](https://eng.uber.com/3d-tiles-loadersgl/)

![image](https://user-images.githubusercontent.com/7025232/71093777-b70dd180-215e-11ea-86f0-66c7ced98b47.png)

**Comment by ibgreen** [comment]
@m-schuetz We talked to the Hobu / Entwine folks and they indicated you have done a lot of work on advanced rendering techniques for point clouds. 

On the deck.gl side we have a good handle on the loading of points, but our [`PointCloudLayer`](https://deck.gl/#/documentation/deckgl-api-reference/layers/point-cloud-layer) which is the primitive layer use to render all the point cloud tiles, just does basic 3D rendering.

It does not yet use any fancy point cloud rendering techniques, maybe you have some pointers for us that could help us improve our visuals?

**Comment by m-schuetz** [comment]
@ibgreen  Hi, sorry for the late reply. Regarding visualization, I think that one of the most important and relatively cheap techniques is Eye-Dome-Lighting:

- https://tel.archives-ouvertes.fr/tel-00438464/document (chapter 4)
- https://blog.kitware.com/eye-dome-lighting-a-non-photorealistic-shading-technique/
- https://www.esri.com/arcgis-blog/products/arcgis-pro/3d-gis/eye-dome-lighting/


- EDL in Potree: https://github.com/potree/potree/blob/develop/src/materials/shaders/edl.fs
- Potree's EDL is based on this implementation in Cloud Compare: https://github.com/CloudCompare/CloudCompare/blob/069c9451fd2af5ca1fca9fde1bfe4fe0b14e139d/plugins/core/GL/qEDL/shaders/EDL/edl_shade.frag


Another great algorithm to improve visualization is "High-Quality Surface Splatting on Today’s GPUs". Instead of only rendering the closest fragments, this method blends overlapping fragments together. It gets rid of the worst aliasing artifacts on surfaces, albeit not on sillhouettes. It's also rather expensive so I usually deactivate it by default to accomodate users without high-end GPUs. 
- https://www.graphics.rwth-aachen.de/media/papers/splatting1.pdf

**Comment by m-schuetz** [comment]
Btw, the changes to the file format are probably going to be bigger than initially expected. I'd like to take this opportunity to change it so that it outputs a single file for all nodes, rather than one file per node. It's quite a bit of work to get there, though.

**Comment by paujar** [comment]
Is this actually coming to 4.2 then if it was partially implemented in 4.1?

**Comment by ibgreen** [comment]
@paujar Thanks for your interest. Unfortunately I am not expecting any movement on the potree format at this time.

- The partial potree implementation was done 5 years ago and not much has happened since then.
- The sense then was that since potree is relatively speaking such a simple format, and we have implementations for the much more complicated I3S and 3D Tiles formats, it would not be much work to complete the support for potree.
- While I'd personally love to see potree supported, I have not been able to get back to it, and there has never been enough interest from any contributor or commercial user of deck.gl to actually make this happen.

If it is truly important to your business, there are teams like Action Engine that have been doing paid work on loaders.gl for years and I am sure they could complete a small effort like this for very modest price.
