### ISSUE TITLE
Tracker: 3.2 release

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2126]
A #772 

- [x] Broken point cloud example.
- [x] Broken 3d tiles example.
- [x] Testing (esbuild scripts etc).
- [x] Test integration deck.gl
- [x] Docs / what's new

#### Node.js worker support
- [x] worker-utils: Node worker basic support 
- [x] Node workers for DracoWriter
- [x] Node workers for KTXWriter
- [x] tests for crypto + compression workers under Node.js
- [x] tile-converter: Use Node.js workers

### Better schemas
- [x] geospatial loaders
