### ISSUE TITLE
Tracker: v4.0 release checklist

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2359]
### v4.0
- [ ] Unbreak Node Workers
  - [ ] yarn test node-debug broken
  - [ ] https://github.com/visgl/loaders.gl/issues/2735 **P0** @belom88  
  - [ ] Restore all tests https://github.com/search?q=repo%3Avisgl%2Floaders.gl+%22TODO+v4%22&type=code
- [ ] Audit
  - [ ] shape changes to loaders
- [ ] Tests
  - [ ] Test Website
  - [x] Test all examples
  - [ ] Update bundler examples
  - [ ] Update CONTRIBUTING and developer guides.
  - [x] Bump in luma.gl v9
  - [x] Bump in deck.gl v9
  - [ ] Bump in deck.gl v8.10
- [x] Docs and Cleanup
  - [ ] Document any changes to shapes
  - [x] Update release notes to cover action engine work **P0** @dsavinov-actionengine 
  - [x] Document polyfills updates for Node v18 and v20 @ibgreen 
- [ ] Loader upgrades
  - [ ] Laz-Perf v0.0.6 @ibgreen (check if needed to restore tests)
  - [x] Draco v1.5.6 @ibgreen
- [x] Deprecations
  - [x] Remove `loadImage` etc from `@loaders.gl/images` (now in `textures`)
- [x] Typing and doc improvements
  - [x] Tighten up loader shapes and return specific types **P0**
  - [x] Add Types to Writers **P0**
  - [x] Support typed Writers **P0**
  - [x] Better typing for GeoJSON  binary utils
  - [x] Add types to ArrowLoader **P0** #2423 
  - [x] Add types to most loaders **P0** #2423 
  - [x] Support typed loaders **P0** 
  - [x] Firm up GLTFLoader types
- [x] New loaders
  - [x] Strongly typed TilesetJSON and TileJSON in `tiles` module **P0** @belom88 
  - [x] pmtiles
  - [x] geoparquet (experimental) 
- [x] Schema improvements
  - [x] Add support "Transferable" Schemas (parallel to Arrow Schemas) **P0**
  - [x] arrowjs v13 **P0** -blocked  https://github.com/visgl/loaders.gl/pull/2632
- [x] Platform and packaging
  - [x] Support Node 18 - upgrade build tools (ocular-devtools v2)
  - [x] Support Node 18 - Align with built-in fetch
  - [x] Support Node 20 in CI (P1)
  - [x] Support ecmascript modules **P0**
  - [x] Move node dependent code to `@loaders.gl/polyfills`
  - [x] Replace use of `md5` with `MD5Hash` in `i3s` module. **P1** @dariaterekhovaae 
  - [x] Rename `Buffer` in 3d tiles: https://github.com/visgl/loaders.gl/blame/master/modules/3d-tiles/src/types.ts#L361
  - [x] Remove use of `Buffer` from `i3s` module. **P1** @dariaterekhovaae https://github.com/visgl/loaders.gl/pull/2500
- [x] Capabilities
  - [x] Support Node.js workers in `@loaders.gl/worker-utils` **P0**
