### ISSUE TITLE
Tracker: v3.4 Release Checklist

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2360]
Testing
- [x] Test with deck.gl WMS layer

Post release
- [x] Restore disabled I3S tests 

Older issues:
- [ ] MVTLoader tests fail under Safari? (`yarn test browser, open localhost:5000 in Safari`) P1 
- [x] deck.gl double check
    - [x] Update playground example to not import and register DracoLoader  @belom88 
    - [x] Update pydeck examples to not import and register DracoLoader  @belom88 
    - [x] Remove draco install from package.json files @belom88
