### ISSUE TITLE
Tracker Website issues after docusaurus upgrade.

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2411]
Examples:
- [x] I3S ArgGIS example broken **P0**
- [ ] GLTF example has rough edges (currently hidden) **P2**
- [ ] Styling on stats widget in I3S examples (too wide) **P0**

Website
- [x] Example thumbnail sizes on examples page **P1** #2412 

Broken links, please list here:
- [ ] All links in docs/specifications/..
- [ ] EXT_meshopt_compression
- [ ] /docs/modules/i3s API links
- [ ] /docs/modules/images, image-utilities links
- [ ] All links in API Reference - Overview in every module
- [ ] point data format
- [ ] Loader catalog - all relative links
- [ ] [IPC: Encapsulated Message Format](http://arrow.apache.org/docs/ipc.html) in arrow loader
- [ ] [FlatGeobuf](https://bjornharrtell.github.io/flatgeobuf/) 
- [ ] Parquet - file format
- [ ] Mapzen Terrain tiles
- [ ] KTX2BasisUniversalTextureWriter data format
- [ ] Compressed texture loder - file format links
- [ ] PLY loader file format
- [ ] Parquet loader file format

**Comment by ibgreen** [comment]
@Tamrat-B please report anything else you see here, we'll fix asap

**Comment by ibgreen** [comment]
This is a tracker task, it should not be closed until all issues are fixed.

**Comment by ibgreen** [comment]
@Pessimistress Have you noticed anything similar in deck.gl after the transition (loss of resolution, antialiasing etc)?

**Comment by Pessimistress** [comment]
No. I don't see any issue from my box, though.
