### ISSUE TITLE
Tracker: examples

### ISSUE THREAD

**Issue by xintongxia** [visgl/loaders.gl#253]
### 2.1
- [ ] Fix filedrop
- [ ] Simplify Metrics and metrics panel

### 1.3

- [x] pointcloud example: separate out mesh layers
- [x] ionAccessToken can not be passed from webpack config
- [x] minimum loader examples
- [x] 3d tiles example: correctly display instanced 3d tile examples
- [x] gltf example: Breakdown example into main and control-panel files

### 1.2
- [x] stats not update correctly
- [x] auto extract viewport from tileset file
- [x] load instanced 3d tile examples
