### ISSUE TITLE
Tracker: snyk security issues

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2581]
Potential security issue (of various severity) reported by the snyk scanner run on application built on loaders.gl.

- [x] fast-xml-parse > 4.1.2 https://github.com/visgl/loaders.gl/pull/2537 - Fixed in 3.4.9
- [x] @xmldom/xlmdom > 0.7.7 https://github.com/visgl/loaders.gl/pull/2580 - Targeted for 3.4.10
- [x] jpeg-js > 0.4.4. Indirect dependency, yarn.lock or kepler.gl resolution pin issue? - 
- [x] request: no resolution - used by jpeg-js. One possible solution is to replace jpeg-js with squoosh.
- [x] qs - various resolutions for each minor version - At least for loaders, yarn.lock refresh should be sufficient.
- [x] json-schema - this is just a dev dependency coming in through `coveralls` via `ocular-dev-tools`
