### ISSUE TITLE
Tracker: @loaders.gl/images

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#279]
### v2.x
- [x] Move `ImageLoader` to a separate `@loaders.gl/image` module.

### v2.1

Docs
- [ ] Document what image formats are supported for the `ImageLoader`
- [ ] Document what image formats are supported for the functions like the image type detection util (that extracts MIME type and size) #276 
- [x] Write Image category docs

Tests/Examples
- [ ] Add example with one test file for each of the supported formats, to show that they loads in Chrome etc. See https://toji.github.io/texture-tester/

Code
- [x] `ImageLoader` worker support with throughput benchmarks
- [x] Data textures: `options.image.data` #597
- [x] Add test cases to `BasisLoader` #596
- [x] Fix `ImageBitmap` support
- [x] Support path prefix #541

### v2.0
- [x] Making image loaders into pure async data parsers (i.e remove `loadAndParse` from loaders.gl).
