### ISSUE TITLE
Tracker: Parquet Support

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#2964]
This tracker issue looks at Parquet support work items

Note that we have both a JS Parser and a WASM parser for parquet. While the WASM parser is expected to remain the more performant and recommended option, note that work on the JS Parser did receive minor one-time funding by OGC to ensure a pure JS GeoParquet implementation exists, as WASM can complicate bundling/maintenance etc..

### JS Parser

- [ ] Feature Matrix in docs https://loaders.gl/docs/modules/parquet/formats/parquet - Update / Implement
- [ ] Add tests for: lz4, lz4_raw
- [ ] Benchmarks
- [ ] JS Parser: LZO Compression - deprecated? Maybe we can try https://github.com/tidepool-org/lzo-wasm?
- [ ] JS Parser: Performance improvements - **P2**
- [ ] JS Parser: Memory improvements JS - **P2**
- [ ] JSParser: Binary output (Convert to Apache Arrow)
- [ ] JSParser: Stay aligned with work in other forks
