### ISSUE TITLE
Tracker: Row based Table Loaders: CSV, JSON, YAML...

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#303]
This issue tracks remaining work for the table category of loaders

# loaders.gl v2.1

### @loaders.gl/core

- [x] Finalize streaming (`parseInBatches`/`loadInBatches`) architecture, implementation and docs. (@ibgreen)

### @loaders.gl/tables (New Table category module)

- [x] Rename `@loaders.gl/experimental` module to `@loaders.gl/tables` (@ibgreen)
- [ ] Document `TableBatch`, schema etc in `@loaders.gl/tables` (@ibgreen) 

General Options
- [x] Add `table.rowType: 'object'/'array'? whether table loaders returns arrays or objects @ibgreen

### ArrowLoader

- [x] Define metadata mappings

### CSVLoader

- [x] Add `csv.rowType: 'object'/'array'? whether table loaders returns arrays or objects (For CSV with header the async parser currently returns arrays...) see table category @ibgreen
- [x] Keep Papaparse? We have some indication that there is a faster CSV parser available (at least for the "external" CSV to "internal" Arrow case), so maybe we shouldn't invest too much in this implementation. @ibgreen 

### `JSONTableLoader`

- [x] Incremental/streaming JSONLoader (based on clarinet or jsonstream?) (@ibgreen)
- [x] Minimal implementation of JSONPath
- [ ] WorkerLoader setup 
- [x] Keep separate `JSONLoader` / `JSONTableLoader` or just use options

### `XMLTableLoader` P2

- [ ] Incremental/streaming XMLLoader (based on sax-js?) (@ibgreen)
