### ISSUE TITLE
Tracker: 3d-tiles traversal and culling issues

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#356]
There are indications that we might be including too many tiles during traversal (which obviously will negatively affect loading and rendering performance). Based on suggestions from @loshjawrence:

General debugging tools for culling
- [ ] Break out a second debug camera out from the render camera
- [ ] Draw debug outline meshes for tile bounding boxes and view frustum

Less costly approaches:
- [ ] For culling maybe edit the camera transform so its pushed back from where it should be, then the culling planes would occupy a smaller space on the screen and you can hopefully see the tiles getting cullled when they move to the edge of the screen (before they actually go off)
- [ ] Maybe edit the tile color to be the current closests distance to any cullling plane
-[ ] Color the tile based on its bounding radius/diagonal relative to the root's bounding radius/diagonal. hopefully gets darker as you go down the tree
unfortunately the problem is probably deeper than what any of this would reveal.

Possible investigations tracks:
- [ ] For region-based bounding boxes, ensure we transform into optimal BoundingSpheres or OBBs. (@xintongxia)
- [ ] Add `Tileset3d.stats` indicators to indicate if any tiles in tileset use regions and other features that may be suspected to cause issues (@xintongxia)

**Comment by ibgreen** [comment]
@Avnerus FYI

**Comment by Avnerus** [comment]
Thanks. I have actually been running that dual camera/bounding boxes technique in my Three.JS viewer (which I hope to be able to open source in the future). In the current state I think culling works rather well (and works much better once `throttleRequests` is enabled). The primary cause for traversing tiles that are not visible is the nature of 'base traversal', so I am hoping [a skip traversal implementation would improve that state](https://cesium.com/blog/2017/05/05/skipping-levels-of-detail/).
One caveat in regards to loaders.gl and skip traversal is that it requires (at least in the Cesium implementation) the use of the stencil buffer, which is specific to the renderer. However there are some fixes that should be done in loaders.gl to enable support for skip traversal, such as storing the 'selection depth' of each tile (to be used later in a stencil test).

**Comment by ibgreen** [comment]
To be honest, I am not sure understand how tile skipping is supposed to work. 
- It seems the major goal is to avoid the overhead of loading parent tiles that are not actually shown.
- I assume this is only applicable in REPLACE refinement mode.
- It is not clear to me that we do load those tiles right now. 
- We do a traversal based on the view frustum, and load the resulting tiles.
- does that not exclude parent tiles in REPLACEMENT mode?

I am not sure I understand why a stencil buffer is needed.

**Comment by ibgreen** [comment]
Moved to #1246.
