### ISSUE TITLE
Tracker: @loaders.gl/core

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#361]
### worker support
- [x] Set up `yarn start-local` or `yarn start-local-worker` to use local workers. 
- [ ] Add documentation about how to copy worker scripts to app to avoid relying on CDN (partly done)
- [ ] Add `debug` option to debug workers - add logging and/or break in debugger
- [ ] Finalize worker override system/security audit (options vs dedicated API etc)
- [ ] New API `initializeWorkers([DracoWorkerLoader, ...])` (let app preload worker scripts before parsing is needed for reduced "time to first pixel")
- [ ] Better control of max concurrency (global options, per-loader options, auto detect number of cores, ...)

### stats
- [ ] time worker startup times
- [ ] time parsers
- [ ] Export stats object from loaders.gl
- [ ] Total time in parsers
- [ ] Total time in parsers on main thread
- [ ] Time to first data (SSL initialization etc)

### embedded binaries
- [ ] Flag to indicate whether binary loader supports offsets or whether arraybuffer copy is needed before invocation?
- [ ] Implement arraybuffer copy before call if needed (auto detect alignment issues?)
- [ ] DracoLoader: Binary test function handle typed arrays with offsets (embedded binaries): `byteOffset`, `byteLength`
- [ ] Ability to parse embedded binaries on workers (byteOffset, byteLength) (copy and transfer?)
- [x] Binary test function handle typed arrays with offsets (embedded binaries): `byteOffset`, `byteLength`

## v2.0

- [x] Build ES6/ES2018 debug workers for all loaders
- [x] Build ES6/ES2018 debug workers - Draco only
- [x] Conditional workers (Image only when imagebitmap output, CSV, JSON only when binary output etc)  @ibgreen
- [x] Update worker override system (loader-specific options) @ibgreen 
- [x] Conditional worker support: `loader.useWorker(options)` @ibgreen
- [x] Support calling "worker parsers" from other worker parsers @Pessimistress 
- [x] Support calling "async parsers" from workers @Pessimistress 

### loader objects
- [x] Remove `loadAndParse`

### loader registry and selection
- [x] registry is currently a map with each extension, which causes same loader to be tests many times...
- [x] More rigorous selection, documented semantics, public API
