### ISSUE TITLE
Tracker: @loaders.gl/textures (basis and compressed textures)

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#501]
# v.Next

### Compressed Texture Support

- [x] Support range of compressed texture formats
- [x] Well-defined data return format for textures https://github.com/visgl/loaders.gl/pull/1983

### Alignment with `@loaders.gl/images`, especially `loadImage...` APIs

- [x] Determine format for loaded mipmap arrays (object with array of data, or array of objects).
- [ ] Add object format for compressed images to list of image types in `@loaders.gl/images` documentation.
- [x] Ensure that `BasisLoader` and `CompressedTextureLoader` return same type of images.

### Basis:

- [x] latest basis decoder
- [x] Support basis encoder (`BasisWriter`)
- [x] KTX2
- [ ] option for specifying supported texture types
- [ ] auto discovery from option.gl (or internally created `gl`?)

# v3.0

- [x] rename module `@loaders.gl/basis` to `@loaders.gl/textures` @ibgreen (#910)
- [x] Implement test application for loaders.gl compressed textures similar to https://toji.github.io/texture-tester/ @dryabinin-actionengine 
- [x] Example that attempts to load various images formats and compressed texture formats using loaders.gl: `load(..., [ImageLoader, CompressedTextureLoader, BasisLoader])`

### Basis:

- [x] Dynamic module loading of basis wasm (@georgios-uber)
- [x] Parsing of images/mip-levels from basis
- [x] Create loader object for basis

### luma.gl/deck.gl integration

- [x] Test that all compressed images can be passed to luma.gl Textures and deck.gl IconLayer etc.

**Comment by belom88** [comment]
> Data return format

What does it mean?

**Comment by ibgreen** [comment]
Make sure all the various (compressed) texture loaders return a consistent type. We took care of it in a recent PR https://github.com/visgl/loaders.gl/pull/1983
