### ISSUE TITLE
Tracker: @loaders.gl/i3s

### ISSUE THREAD

**Issue by xintongxia** [visgl/loaders.gl#506]
Spec
https://github.com/Esri/i3s-spec/blob/7e215b609e1c8e1e43324140f9fca65e64486901/profiles/meshpyramids/meshpyramids.md

Reference
https://github.com/CrashedBboy/i3s-web-client/tree/master/static

v2.1
https://github.com/uber-web/loaders.gl/issues/628

POC
- [x] Unzip slpk data file https://github.com/uber-web/loaders.gl/issues/514
- [x] Travers and parse geometries dataset https://github.com/uber-web/loaders.gl/issues/516
- [x] Render with Cesium Viewer https://github.com/uber-web/loaders.gl/issues/517
- [x] Render with deck.gl MeshLayer (ScenegraphLayer)
- [x] Render dataset with texture and more levels
- [x] Fix traversal and enable Level of Details https://github.com/uber-web/loaders.gl/issues/518
- [x] Fix LoD calculation based on [stackoverflow](https://stackoverflow.com/questions/21648630/radius-of-projected-sphere-in-screen-space)
- [x] Apply request scheduling
- [x] Move to use `3d-tiles` traversal and caching #540 
- [x] Improve/Fix LoD calculation #562
- [x] Debug missing tiles issues when camera is too close to map or tilted map to a certain angle (Base map is not fully covered by tiles, some parts are empty) @jianhuang01 
- [x] Remove requests for fetching featureData, instead extract the attribute layouts from tileset metadata
- [ ] i3s example floating - fix z calculation
- [ ] `I3STileLayer` extends from `Tile3DLayer`
- [ ] Enable debugging and add test cases https://github.com/uber-web/loaders.gl/issues/580
- [ ] Render parent tile before children tiles are present
- [x] Add i3s worker for decoding i3s geometry
- [ ] Consolidate request schedulers to manage tile metadata, and content fetching
- [ ] refactor tile-header and tileset classes, which could be shared by both tiles
- [ ] evaluate the logic of empty tile traversal, tile optimization, tile expiration
- [ ] verify `skipLOD` and `loadSiblings` options.
- [ ] Render with ScenegraphLayer
- [ ] Compressed texture
- [ ] Move CPU calculation to GPU
   - [ ] Minimum height of data positions - using transform feedback
- [x] Enable feature data, e.g. user specified metadata associated with the object (like a building, etc.)
- [ ] Support LOD bias control (fudge factor)

Backlog
- [ ] Create `3d-tiles` catalog with 3d-tiles and i3s as submodule
