### ISSUE TITLE
Tracker: point cloud model rendering issue

### ISSUE THREAD

**Issue by jianhuang01** [visgl/loaders.gl#527]
- [ ] Pitch angle is restricted on 60 degrees
- [ ] Point size has perspective effects, not consistently rendered.
- [ ] Still has minor LOD issue after tuning maximumScreenSpaceError = 8
- [ ] Streaming performance is not ideal
- [ ] Tiles missing for certain pitch angle or high zoom level

**Comment by loshjawrence** [comment]
> Point size has perspective effects, not consistently rendered.

Not sure if this one is alluding to just setting a fixed point size that's a little larger than normal but that experiment should be in this list.

**Comment by jianhuang01** [comment]
> > Point size has perspective effects, not consistently rendered.
> 
> Not sure if this one is alluding to just setting a fixed point size that's a little larger than normal but that experiment should be in this list. It's not an ideal solution but in terms of effort vs ROI, it should be pretty good.

We use deck.gl point cloud layer to render point clouds, the layer has perspective effects(scale point size based on depth) even setting a fixed point size. There could be a parameter in deck.gl layer to tune and fix it.
