### ISSUE TITLE
Tracker: Point Cloud Usability and Polish

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#536]
## v2.x Point cloud category

Also, see discussion at end of #659

- [ ] Goal is to be able to pass output from loader directly to `PointCloudLayer`... 
- [x] Show how this can be implemented by adding a loader-to-deck-conversion-function in the point cloud example (thanks @Gmadges)
- [ ] Add option (`loader.mesh.pointcloud: true')? to mesh loaders to force/ensure that point clouds geometries are returned from loaders for formats that can encode both point clouds and meshes (e.g. OBJLoader...)
- [ ] Add bounds calculation to all the mesh category loaders (there are ~5 of them), then remove that "clutter" from the example.
- [ ] We could just add the pointcloud example's `getBounds` function to each point cloud loader (it is small enough) or we could place a helper in the `loader-utils` module for now, or we could even create a new `@loaders.gl/meshes` "category module" for mesh-related utilities.

## v2.1

Point Cloud Example Features
- [x] Auto calculate center - Current example starts rotating around center that may not be point cloud center (thanks @Gmadges!)
- [x] Auto calculate bounding box - Current example does not adapt to model size (thanks @Gmadges!)
- [x] Support colors - Example throws away all attributes except positions (e.g. colors) (thanks @Gmadges!)

Point Cloud Samples
- [x] No PLY example with color (ideas: get from Sketchfab or convert from other format?)  (thanks @Gmadges)

**Comment by Gmadges** [comment]
I'd like to contribute to this project. I can take a look at this?

**Comment by ibgreen** [comment]
> I'd like to contribute to this project. I can take a look at this?

@Gmadges Of course. Happy to engage with you and help you get started. 

As preparation, to make sure you have a sense for the high-level ideas behind the code you are going to change, you'll want to read up on:
- [Loader Categories](https://loaders.gl/docs/developer-guide/loader-categories)
- [Point Cloud Category](https://loaders.gl/docs/specifications/category-mesh)

And read this code
- [point cloud example](https://github.com/uber-web/loaders.gl/tree/master/examples/deck.gl/pointcloud)

Then we can have a sync and make sure any questions you have get answered, give you some tips for how to proceed etc.

Welcome to loaders.gl!

**Comment by Gmadges** [comment]
Awesome, thank you!
> Then we can have a sync and make sure any questions you have get answered, give you some tips for how to proceed etc.

What is the best method to ask questions? here on this issue?

**Comment by ibgreen** [comment]
> What is the best method to ask questions? here on this issue?

Yes, of course, we can start here. 

You could also sign up for the kepler.gl or deck.gl slack channels. E.g. https://github.com/keplergl/kepler.gl/issues/643

**Comment by ibgreen** [comment]
@Gmadges Many thanks for #659 ! If you want to engage further, my offer of connect on e.g. the slack channel or via other means still stands.

**Comment by ibgreen** [comment]
Mentioning this tracker issue in future release tracker issue, but closing for inactivity
