### ISSUE TITLE
Tracker: Performance

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#57]
### General Perf

- [ ] Add benchmarks for all Parsers...
- [ ] `loader.testText` - requires converting entire file instead of just header

### PLYLoader

- [ ] `PLYLoader` (binary) converts entire buffer to text just to parse header...
