### ISSUE TITLE
Tracker: GLTFLoader

### ISSUE THREAD

**Issue by twojtasz** [visgl/loaders.gl#7]
### v2.x

glTF standards compliant loader: missing features
- [ ] morph/skin/joint animations (@georgios-uber)

### v2.1

Loader Features:
- [ ] Support `basis` subloader (@georgios-uber)

Other
- [ ] Support API simplifications in luma.gl
- [ ] Fix async issue in deck.gl

Tests:
- [ ] Add glTF/GLB test files with base64, linked files, Draco... (@georgios-uber)
- [ ] Unit tests (@georgios-uber)
- [ ] Render tests (@georgios-uber)

Extensions:
- [ ] Test Uber point cloud extension
- [ ] Implement fallback semantics for KHR draco extension per spec (@georgios-uber)
- [ ] Make sure pre-decoded Draco glTF is indistinguishable from non-Draco file (currently attribute descriptors are slightly different).

### v2.0 

- [x] Support `draco` subloader (@ibgree)
- [x] Use nested `options.gltf` (@igbreen)
- [x] Remove v1 glTF parser (@ibgreen)
- [x] Get v2 glTF parser to feature parity with v1 parser (@ibgreen)

Extensions:
- [x] Support material_unlit extension (@ibgreen)

### v1.2

- [x] Refactor: Remove GLTF Accessor/Image knowledge from GLB classes (Separation of concerns).
- [x] Add manual draco mesh decode option for XVIZ.

### v1.0

- [x] change from nopack -> packTypedArray @ibgreen 
- [x] Documentation: Cleanup pass on GLTF docs @ibreen
- [x] Documentation: GLTF extension support (#65) @ibreen
- [x] API Audit: `GLBBuilder`,`GLTFBuilder` - `nopack` option renamed to `packTypedArrays` (#94) @ibreen
- [x] Refactor: Break out non-standard postprocessing from GLTFParser (Separation of concerns). @ibreen
- [x] Feature: `GLTFLoader` & `GLTFParser.parse()` supports async loading of linked resource files and base64 encoded `buffers`. @georgios-uber 	
- [x] Feature: `GLTFParser.parse()` supports the following inputs: ArrayBuffer containing GLB, ArrayBuffer containing UTF8 encoded JSON, string containing JSON as well as decoded JSON. @ibreen

### v0.5.x XVIZ integration
- [x] Draco point cloud support (interface options/docs on how to use / expose)
- [x] Verify functional support parity with existing code or changes in XVIZ as required
- [x] Verify image support in XVIZ
- [x] removal of XVIZ magic header

### v0.4.x Flesh out GLTF support
- [x] move JSON pack/unpack to same layer in stack (`GLTFBuilder`/`GLTFParser`)
- [x] Fluent `GLBBuilder`/`GLTFBuilder` APIs 
- [x] Fluent `GLTFBuilder` API for adding extensions
- [x] Remove custom *jsonKey*, in favor of extensions/extras
