### ISSUE TITLE
Tracker: `RequestScheduler` Roadmap

### ISSUE THREAD

**Issue by ibgreen** [visgl/loaders.gl#754]
There is strong demand for using experimental RequestScheduler in more situations, so we should  overhaul this class.

### Potential features

- Event throttling for Node.js (avoid hitting servers too fast)
    - [ ] Add a "requests/second" limit, don't issue tokens faster than that.
- Retry functionality (for 429 errors and beyond).
    - [ ] Provide a `fetch` like interface so this can be used instead of `fetch`? (We need to actually control the "fetch" not just the "token")
    - [ ] Implement Exponential backoff
- Domain tracking
    - [ ] throttle per domain
    - [ ] domain sharding

### Task List

- [ ] Design the API to support exponential backoff (@kylebarron )
- [x] Document and export `RequestScheduler` (@ibgreen)
- [x] Land the "Simplify RequestScheduler API" PR #672

**Comment by ibgreen** [comment]
@kylebarron @NikolayActionEngine

**Comment by ibgreen** [comment]
Handling 429s with exponential backoff will require actually doing the fetch. If we are OK with this being part of this class, then we could add a `RequestScheduler.fetch()` style API.

Code snippet
<details>
 async fetch(url, fetchOptions, schedulerOptions) {
    const requestToken = await this.scheduleRequest(url);
    // Request was cancelled before a slot was available
    if (!requestToken) {
      return new Response(null, {
        status: 408, // Request Timeout
        statusText: 'Request cancelled by application'
      }); 
    }
    // Issue the request, possibly multiple times
    for (;;) {
      const response = fetchOptions ? await fetch(url, fetchOptions) : await fetch(url);
      // Whether we failed or succeeded, return the response
      const completed = response.ok || response.status !== 429;
      if (completed) {
        requestToken.done(); // NOTE: **must** be called for the next request in queue to resolve
        return response;
      }
      //
      if (response.status !== 429) {
        requestToken.done(); // NOTE: **must** be called for the next request in queue to resolve
        return response;
        // TODO - implement Exponential backoff
        // Finally give up
        return new Response(null, {
          status: 408, // Request Timeout
          statusText: 'Request cancelled by application'  
        });
      }
    }
  }
</details>

**Comment by ibgreen** [comment]
We may want to:
- make sure we can specify alternative versions of fetch. Should likely align with the [Fetch Option RFC](https://github.com/visgl/loaders.gl/blob/master/dev-docs/RFCs/v2.0/fetch-option-rfc.md)
- bind this method so that `requestScheduler.fetch` can be passed around on its own.

**Comment by ibgreen** [comment]
We perhaps also do an intermediate interface that doesn't require fetch overloading

The schedule could return a `reschedule` callback:

```js
let token = await requestScheduler.scheduleRequest(...);

while (token) {
  const {done, reschedule} = token
  const response = await fetch();
  if (request.ok) {
    // process response
    done();
    break;
  }
  if (request.status === 429) {
    token = await reschedule();
  }
}
```

**Comment by ibgreen** [comment]
Mentioning in future task tracker but closing due to inactivity
