### ISSUE TITLE
Tracker: Geospatial Parsers

### ISSUE THREAD

**Issue by kylebarron** [visgl/loaders.gl#759]
### General
- [ ] Document GIS category
- [ ] GeoJSONLoader is included as an experimental export. Documentation needs to be written before the 2.3.0 release.
- [ ] Remove `geojson` extension from `JSONLoader`?
- [ ] Standardize geospatial loader batch format.
...
